### ISSUE TITLE
Expected 3 generic arguments

### ISSUE THREAD

**Issue by uniteddevil** [joeirimpan/hdfc-cc-parser-rs#1]
After running cargo build --release
I am getting this error.

Rust version - rustc 1.68.0 (2c8cc3432 2023-03-06)

   Compiling hdfc-cc-parser-rs v0.1.0 (/Users/gopalyadav/Projects/hdfc-cc-parser-rs)
error[E0107]: this struct takes 3 generic arguments but 1 generic argument was supplied
   --> src/main.rs:39:16
    |
39  |     let file = pdfFile::<Vec<u8>>::open_password(path.clone(), _passwor...
    |                ^^^^^^^   ------- supplied 1 generic argument
    |                |
    |                expected 3 generic arguments
    |
note: struct defined here, with 3 generic parameters: `B`, `OC`, `SC`
   --> /Users/gopalyadav/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/e41c599/pdf/src/file.rs:298:12
    |
298 | pub struct File<B, OC, SC> {
    |            ^^^^ -  --  --
help: add missing generic arguments
    |
39  |     let file = pdfFile::<Vec<u8>, OC, SC>::open_password(path.clone(), _password.as_bytes())
    |                                 ++++++++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `hdfc-cc-parser-rs` due to previous error

**Comment by joeirimpan** [comment]
@uniteddevil I think you might be missing `sudo apt install libstd-rust-dev`. Or you can use the pre-built binary from here https://github.com/joeirimpan/hdfc-cc-parser-rs/releases/download/v0.0.1/hdfc-cc-parser-rs

**Comment by joeirimpan** [comment]
Found the issue. This was because pdf_tools dependency was linking another commit of pdf dependency. I have pushed a change which fixes this. Please check it out.

**Comment by uniteddevil** [comment]
Thanks, resolved.
