### ISSUE TITLE
Generates nothing

### ISSUE THREAD

**Issue by antani** [joeirimpan/hdfc-cc-parser-rs#14]
No output CSV created 
the program instantly exits

`➜  hdfc-cc-parser-rs git:(master) ✗ RUST_LOG=info ./target/release/hdfc-cc-parser-rs --name=",,,," --dir ./statements/
[2024-03-18T16:50:29Z INFO  hdfc_cc_parser_rs] starting main
["./statements/0001015720000521082_01222024_02112024.PDF", "./statements/0001015720000521082_02222024_03132024.PDF", "./statements/0001015720000140487_09222023_10122023.PDF", "./statements/0001015720000521082_11222023_12122023.PDF", "./statements/0001015720000521082_12222023_01112024.PDF", "./statements/0001015720000521082_10222023_11112023.PDF"]
➜  hdfc-cc-parser-rs git:(master) ✗ ls -latr`

I am not sure hwo this file is generating any file - 

`let mut wtr = csv::Writer::from_writer(io::stdout());`

**Comment by joeirimpan** [comment]
`csv::Writer::from_writer(io::stdout())`
It writes the parsed records to stdout like you can see. If you aren't getting any parsed records, it is likely that pdf format is slightly different than what is expected.

Sample result
![image](https://github.com/joeirimpan/hdfc-cc-parser-rs/assets/11286580/512e7f6e-364c-48f6-b967-9d631c1d4802)

**Comment by antani** [comment]
I am downloading infinia statements and using them without password (they
are unlocked)
Let me give it one more try


Thanks,

Ved
