### ISSUE TITLE
Not a directory issue.

### ISSUE THREAD

**Issue by uniteddevil** [joeirimpan/hdfc-cc-parser-rs#2]
https://github.com/joeirimpan/hdfc-cc-parser-rs/blob/710f11e898b351b5b3eaf639c13d46bbce534f7f/src/main.rs#L211

./target/release/hdfc-cc-parser-rs '/Users/go/Downloads/0001015720000331409_02182023_03102023 (1).PDF' '' /Users/gopalyadav/Projects/hdfc-cc-parser-rs/output.csv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: NotADirectory, message: "Not a directory" }', src/main.rs:211:38

**Comment by joeirimpan** [comment]
Can you put the statements into a folder and give the path to the folder instead of the file?

**Comment by uniteddevil** [comment]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:225:64

`let a_date = NaiveDate::parse_from_str(&re.captures(a).unwrap()[1], "%d-%m-%Y").unwrap();`

getting this error now.

Please note my pdf files are not password protected.

**Comment by joeirimpan** [comment]
ah. This assumes that date string is part of the filenames. I will add a fallback for this. Between, i had only tested the parsing logic with regalia, freedom statements.

For quick testing, you can add a date string to the file name in the format mentioned above

**Comment by uniteddevil** [comment]
0001015720000331409_02182023_03102023.pdf - this is for Infinia
0001018360006057604_06182022_07082022.pdf - this is for regalia
0001018360006057604_07182022_08072022.pdf - this is for regalia as well

Script is working for single file. But when all files are there it fails.

**Comment by joeirimpan** [comment]
I have pushed few more changes. Sort, password arguments are optional now
```bash
./hdfc-cc-parser-rs --dir </path/to/statements> --password <optional password> --output <output.csv> --sortformat="optional format eg., %d-%m-%Y"
```
